name: CI
on:
  - push
  - pull_request
jobs:
  dist:
    name: Make distribution using Dist::Inkt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache ~/perl5
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-dist-locallib
          path: ~/perl5
      - name: Perl version
        run: |
          perl -v
      - name: Install cpanm
        run: |
          curl -L https://cpanmin.us | perl - --sudo App::cpanminus
      - name: Install local::lib
        run: |
          cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
      - name: Install Dist::Inkt
        shell: bash
        run: |
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          cpanm -n Dist::Inkt::Profile::TOBYINK
      - name: Make distribution
        shell: bash
        run: |
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          ~/perl5/bin/distinkt-dist --TRAVIS --targetdir=build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./
  inspect:
    name: Inspect distribution
    needs: dist
    runs-on: ubuntu-latest
    steps:
      - name: Get dist artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Install dependencies
        run: |
          sudo apt install tree
      - name: Tree
        run: |
          tree build
      - name: Changes
        run: cat build/Changes
      - name: COPYRIGHT
        run: cat build/COPYRIGHT
      - name: CREDITS
        run: cat build/CREDITS
      - name: doap.ttl
        run: cat build/doap.ttl
      - name: Makefile.PL
        run: cat build/Makefile.PL
      - name: META.json
        run: cat build/META.json
      - name: META.yml
        run: cat build/META.yml
  test:
    name: Perl ${{ matrix.perl }} ${{ matrix.os }} [thr=${{ matrix.threaded }}] ${{ matrix.joblabel }}
    needs: dist
    runs-on: ${{ matrix.os }}-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      CODECOV_TOKEN:        ${{ secrets.CODECOV_TOKEN }}
      GHA_TESTING_MODE:     ${{ matrix.extended_testing }}
      GHA_TESTING_COVER:    ${{ matrix.coverage }}
    strategy:
      fail-fast: true
      matrix:
        os:                 [ 'ubuntu' ]
        perl:               [ '5.8', '5.10', '5.12', '5.14', '5.16', '5.18', '5.20', '5.22', '5.24', '5.26', '5.28', '5.30', '5.32' ]
        threaded:           [ true, false ]
        coverage:           [ false ]
        extra_dependencies: [ true ]
        extended_testing:   [ 'extended' ]
        exclude:
          - { os: 'windows', perl: '5.8' }
          - { os: 'windows', perl: '5.10' }
          - { os: 'windows', perl: '5.12' }
        include:
          - os: ubuntu
            perl: '5.30'
            threaded: false
            coverage: true
            extra_dependencies: true
            extended_testing: 'both'
            joblabel: '(Coverage)'
          - { os: 'macos',   perl: '5.14', threaded: false }
          - { os: 'macos',   perl: '5.24', threaded: false }
          - { os: 'macos',   perl: '5.32', threaded: false }
          - { os: 'macos',   perl: '5.14', threaded: true }
          - { os: 'macos',   perl: '5.24', threaded: true }
          - { os: 'macos',   perl: '5.32', threaded: true }
          - { os: 'windows', perl: '5.14', threaded: true }
          - { os: 'windows', perl: '5.24', threaded: true }
          - { os: 'windows', perl: '5.32', threaded: true }
    steps:
      - name: Get dist artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          multi-thread: ${{ matrix.threaded }}
      - name: Perl version
        run: |
          perl -v
      - name: Configure
        working-directory: ./build/
        run: perl Makefile.PL
      - name: Install dependencies
        run: |
          cpanm -n --installdeps ./build
          cpanm App::GhaProve
      - name: Install extra dependencies
        if: matrix.extra_dependencies || matrix.coverage
        run: cpanm -n --installdeps --with-recommends --with-suggests ./build
      - name: Install coverage dependencies
        if: matrix.coverage
        run: |
          cpanm -n Devel::Cover
          cpanm -n Devel::Cover::Report::Coveralls
          cpanm -n Devel::Cover::Report::Codecov
      - name: Make
        working-directory: ./build/
        run: make
      - name: Clean coverage data
        if: matrix.coverage
        working-directory: ./build/
        run: cover -delete
      - name: Install optional deps for better test coverage
        if: matrix.coverage
        run: |
          cpanm -n match::simple
          cpanm -n Class::InsideOut
          cpanm -n Data::Constraint
          cpanm -n Devel::Hide Devel::RefCount
          cpanm -n Function::Parameters
          cpanm -n IO::String
          cpanm -n Kavorka
          cpanm -n Moops
          cpanm -n MooseX::Getopt
          cpanm -n MooseX::Types MooseX::Types::Common
          cpanm -n MooX::TypeTiny
          cpanm -n MouseX::Types MouseX::Types::Common
          cpanm -n Object::Accessor
          cpanm -n Return::Type
          cpanm -n Specio
          cpanm -n Switcheroo
          cpanm -n Validation::Simple
      - name: Test suite (No XS, LaxNum)
        working-directory: ./build/
        env:
          PERL_ONLY: 1
          PERL_TYPE_TINY_XS: 0
          PERL_TYPES_STANDARD_STRICTNUM: 0
        run: gha-prove -Iinc -b -r t
      - name: Test suite (No XS, StrictNum)
        working-directory: ./build/
        env:
          PERL_ONLY: 1
          PERL_TYPE_TINY_XS: 0
          PERL_TYPES_STANDARD_STRICTNUM: 1
        run: gha-prove -Iinc -b -r t
      - name: Install Type::Tiny::XS
        shell: bash
        run: cpanm Type::Tiny::XS || echo 1
      - name: Test suite (XS, LaxNum)
        working-directory: ./build/
        env:
          PERL_ONLY: 0
          PERL_TYPE_TINY_XS: 1
          PERL_TYPES_STANDARD_STRICTNUM: 0
        run: gha-prove -Iinc -b -r t
      - name: Test suite (XS, StrictNum)
        working-directory: ./build/
        env:
          PERL_ONLY: 0
          PERL_TYPE_TINY_XS: 1
          PERL_TYPES_STANDARD_STRICTNUM: 1
        run: gha-prove -Iinc -b -r t
      - name: Coveralls.io report
        if: success() && matrix.coverage
        working-directory: ./build/
        run: cover -select_re '^lib/' -report coveralls
      - name: Codecov.io report
        if: success() && matrix.coverage
        working-directory: ./build/
        run: cover -select_re '^lib/' -report codecov
